line-length = 100
target-version = "py310"
output-format = "concise"

[lint]
select = ["ALL"]

ignore = [
    "COM812", "ISC001", # conflicts with formatter
    "D203", "D212", "D213", "D214", "D215",  # conflicts with PEP257-convention (A)
    "D404", "D405", "D406", "D407", "D408", "D409",  # conflicts with PEP257-convention (B)
    "D410", "D411", "D413", "D415", "D416", "D417",  # conflicts with PEP257-convention (C)
    "N802", "N803", "N806", "N815", "N816", # naming (si-units should stay)
    "PLR2004", # magic values
    "T201",   # allow print
    "N999",  # invalid module name
    "ERA001",  # commented-out code
]

exclude= [
]

[lint.per-file-ignores]
#"*/tests/**" = ["ARG", "S", "D", "SLF001"]

[lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[lint.isort]
force-single-line = true

[lint.pyupgrade]
keep-runtime-typing = true

[format] # per default like Black
docstring-code-format = true
